name: Docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Lint Check
        run: |
          pnpm install
          pnpm lint:check

  markdown-link-check:
    name: Check Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.12
